version: 2

models:
  - name: dim_operator
    description: "Unique airline operators"
    columns:
      - name: operator_id
        description: "Surrogate key for each operator"
      - name: operator
        description: "Airline or organization operating the aircraft"
